# Generated by Django 3.1.1 on 2020-11-09 09:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Email',
            new_name='Emails',
        ),
    ]
