# Generated by Django 3.1.1 on 2020-11-25 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0003_emailtoagent'),
    ]

    operations = [
        migrations.AddField(
            model_name='emails',
            name='is_replied',
            field=models.BooleanField(default=False),
        ),
    ]
