# Generated by Django 3.1.1 on 2020-10-14 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0005_property_short_description'),
        ('profiles', '0005_auto_20201014_0912'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='my_favorities',
            field=models.ManyToManyField(related_name='user_liked', to='property.Property'),
        ),
    ]
