# Generated by Django 3.1.1 on 2020-10-15 16:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0006_profile_my_favorities'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MyFavorites',
        ),
    ]
