# Generated by Django 3.1.1 on 2020-11-18 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0016_auto_20201118_2238'),
        ('profiles', '0009_auto_20201117_0958'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='my_favorities',
            field=models.ManyToManyField(blank=True, related_name='user_liked', to='property.Property'),
        ),
    ]
