# Generated by Django 3.1.1 on 2020-11-17 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=40)),
                ('image', models.ImageField(upload_to='agents')),
                ('about_agent', models.TextField()),
                ('phone', models.CharField(max_length=20)),
                ('email_address', models.EmailField(max_length=254)),
                ('occpupation', models.CharField(max_length=40)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('update_at', models.DateField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Team Members',
            },
        ),
        migrations.DeleteModel(
            name='Agent',
        ),
    ]
