# Generated by Django 3.1.1 on 2020-11-17 09:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0003_auto_20201117_0007'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Team',
        ),
    ]
