"""
Django settings for castle project.

Generated by 'django-admin startproject' using Django 3.0.5.

For more information on this file, see
https://docs.djangoproject.com/en/3.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.0/ref/settings/
"""

import os
import django_heroku


# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
SITE_PROTOCOL =  True
META_SITE_PROTOCOL = 'https'
META_SITE_DOMAIN = True

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/3.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'l#y!q1w6v&0i$%&^34%(1aosewv%qew$@t1%))e33-+xk=wxd$'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = False    
ALLOWED_HOSTS = ['castle787.herokuapp.com']


SECURE_SSL_REDIRECT = True
# SESSION_COOKIE_SECURE = False
# CSRF_COOKIE_SECURE = False
# SECURE_HSTS_SECONDS = 1
# SECURE_HSTS_INCLUDE_SUBDOMAINS = True
# SECURE_HSTS_PRELOAD =  True


SITE_ID = 1

SILENCED_SYSTEM_CHECKS = ['models.E001']
# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.sites',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'sitetree',
    'taggit',
    'ckeditor',
    'ckeditor_uploader',
    'news',
    'allauth',
    'allauth.account',
    'allauth.socialaccount',   
    'profiles',
    'property',
    'pages',
    'meta',
    'django_simple_cookie_consent',
    'contacts',
    'additions',
    'agents',
    'admin_honeypot',
    'backoffice',
    'easy_thumbnails',
    'columns',  
    'widget_tweaks',
    'django_twilio',
    'django.contrib.postgres',
    'rentals',
    'djrichtextfield',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
]

ROOT_URLCONF = 'castle.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [
            os.path.join(BASE_DIR, 'templates/castle')
        ],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'castle.wsgi.application'


# Database
# https://docs.djangoproject.com/en/3.0/ref/settings/#databases

DATABASES = {
    # 'default': {
    #     'ENGINE': 'django.db.backends.sqlite3',
    #     'NAME': os.path.join(BASE_DIR, 'db.sqlite3'),
    # }

       'default': {
        'ENGINE': 'django.db.backends.postgresql_psycopg2',
        'NAME': 'castel',
        'USER': 'castel',
        'PASSWORD': 'Adgjmptw',
        'HOST': '',
        'PORT': '',
    }
}


# Password validation
# https://docs.djangoproject.com/en/3.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# Memache settings for those who prefer memache
CACHES = {"memcached": {
                        "BACKEND":"django.core.cache.backends.memcached.MemcachedCache",
                        "LOCATION": "localhost:11211",
                        "TIMEOUT": 60,  # 1 minute
                        "KEY_PREFIX": "myproject",
                        },
}

CACHES["default"] = CACHES["memcached"]


# CACHES = {
#         "redis": {
#                 "BACKEND": "redis_cache.RedisCache",
#                 "LOCATION": ['localhost:6379'],
#                 "TIMEOUT": 60, # 1 minute
#                 "KEY_PREFIX": "myproject",
#         },
# }

# CACHES["default"] = CACHES["redis"]

# Internationalization
# https://docs.djangoproject.com/en/3.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True

ACCOUNT_FORMS = {'signup': 'forms.SignupForm.MyCustomSignupForm'}


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/3.0/howto/static-files/

STATIC_URL = '/static/'

STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')

STATICFILES_DIRS =(
        os.path.join(BASE_DIR, 'static'),
    )

STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'

MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media/')

CKEDITOR_UPLOAD_PATH='uploads/'

CKEDITOR_CONFIGS = {
    'default': {
        'toolbar': 'Advanced',
         'forcePasteAsPlainText': True,

    },
    'basic':{
        'toolbar': 'Basic'
    }
}

EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_HOST_USER = 'cloud.berdiyev@gmail.com'
EMAIL_HOST_PASSWORD = 'AdgjmptwwtpmjgdA' #past the key or password app here
EMAIL_PORT = 587
EMAIL_USE_TLS = True
DEFAULT_FROM_EMAIL = 'default from email'


admin_email = 'admin@admin.ru'


LOGIN_REDIRECT_URL = 'profile:profile'
# LOGIN_URL = 'accounts:login'
# LOGOUT_URL = 'accounts:logout'

EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'

django_heroku.settings(locals())