# Generated by Django 3.1.1 on 2020-11-09 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('additions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partners',
            name='priportiy',
            field=models.IntegerField(),
        ),
    ]
