# Generated by Django 3.1.1 on 2020-11-09 23:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('additions', '0004_auto_20201109_2304'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='faq',
            options={'verbose_name_plural': 'FAQs'},
        ),
        migrations.AlterModelOptions(
            name='partners',
            options={'verbose_name_plural': 'Partners'},
        ),
        migrations.RenameField(
            model_name='partners',
            old_name='priportiy',
            new_name='priortiy',
        ),
    ]
