# Generated by Django 3.1.1 on 2020-11-09 23:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('additions', '0005_auto_20201109_2346'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='faq',
            options={'ordering': ['priority'], 'verbose_name_plural': 'FAQs'},
        ),
        migrations.AlterModelOptions(
            name='partners',
            options={'ordering': ['priority'], 'verbose_name_plural': 'Partners'},
        ),
        migrations.RenameField(
            model_name='partners',
            old_name='priortiy',
            new_name='priority',
        ),
    ]
