# Generated by Django 3.0.11 on 2020-11-26 09:28

import ckeditor.fields
from decimal import Decimal
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import rentals.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Feature',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('created', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255)),
                ('phone_number', models.CharField(blank=True, max_length=17, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')])),
                ('email', models.EmailField(max_length=254)),
                ('message', models.TextField()),
                ('status', models.CharField(choices=[('0', 'Not Replayed'), ('1', 'Replayed')], default='0', max_length=50)),
                ('created', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='PropertyCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('created', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='ReplyMessage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('reply_message', models.TextField()),
                ('created', models.DateTimeField(auto_now=True)),
                ('message', models.ManyToManyField(to='rentals.Message')),
                ('user', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Properties',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('size', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('price', models.DecimalField(decimal_places=2, max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('bedroom', models.PositiveIntegerField(default=1)),
                ('bathroom', models.PositiveIntegerField(blank=True, null=True)),
                ('available_from', models.DateField()),
                ('status', models.CharField(choices=[('0', 'Not Available'), ('1', 'Available')], default='1', max_length=25)),
                ('purpose', models.CharField(choices=[('0', 'Rent'), ('1', 'Sale')], default='1', max_length=25)),
                ('year_built', models.PositiveIntegerField()),
                ('garage', models.PositiveIntegerField(blank=True, default=0)),
                ('floor', models.PositiveIntegerField()),
                ('total_floor', models.PositiveIntegerField(default=1)),
                ('internet', models.CharField(blank=True, max_length=50)),
                ('description', ckeditor.fields.RichTextField()),
                ('pet_policy', models.CharField(choices=[('0', 'Not Allowed'), ('1', 'Allowed'), ('2', 'Unknown')], default='0', max_length=50)),
                ('created', models.DateTimeField(auto_now=True)),
                ('featured', models.BooleanField(default=False)),
                ('house_number', models.CharField(blank=True, max_length=255)),
                ('street', models.CharField(max_length=255)),
                ('city', models.CharField(blank=True, max_length=255)),
                ('region', models.CharField(blank=True, max_length=255)),
                ('postal_Code', models.CharField(blank=True, max_length=255)),
                ('country', models.CharField(max_length=255)),
                ('latitude', models.DecimalField(decimal_places=16, max_digits=22)),
                ('longitude', models.DecimalField(decimal_places=16, max_digits=22)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='rentals.PropertyCategory')),
                ('feature', models.ManyToManyField(blank=True, to='rentals.Feature')),
            ],
        ),
        migrations.CreateModel(
            name='Picture',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('picture', models.FileField(blank=True, null=True, upload_to=rentals.models.upload_image_path, validators=[rentals.models.validate_file_extension])),
                ('created', models.DateTimeField(auto_now=True)),
                ('properties', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rentals.Properties')),
            ],
        ),
        migrations.AddField(
            model_name='message',
            name='properties',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rentals.Properties'),
        ),
    ]
