# Generated by Django 3.1.3 on 2020-11-26 10:45

from django.db import migrations, models
import rentals.models


class Migration(migrations.Migration):

    dependencies = [
        ('rentals', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='picture',
            name='picture',
            field=models.FileField(blank=True, null=True, upload_to=rentals.models.upload_image_path),
        ),
    ]
