# Generated by Django 3.1.1 on 2020-10-12 10:58

import ckeditor.fields
from decimal import Decimal
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('house_number', models.CharField(blank=True, max_length=255)),
                ('street', models.CharField(max_length=255)),
                ('city', models.CharField(blank=True, max_length=255)),
                ('region', models.CharField(blank=True, max_length=255)),
                ('postal_Code', models.CharField(blank=True, max_length=255)),
                ('country', models.CharField(max_length=255)),
                ('latitude', models.DecimalField(decimal_places=16, max_digits=22)),
                ('longitude', models.DecimalField(decimal_places=16, max_digits=22)),
                ('address_description', ckeditor.fields.RichTextField(blank=True)),
                ('created', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Feature',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('created', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Picture',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('picture', models.ImageField(blank=True, null=True, upload_to='')),
                ('created', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='PropertyCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('created', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('size', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('price', models.DecimalField(decimal_places=2, max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('bedroom', models.PositiveIntegerField(default=1)),
                ('bathroom', models.PositiveIntegerField(blank=True)),
                ('available_from', models.DateField()),
                ('status', models.CharField(choices=[('0', 'Not Available'), ('1', 'Available')], default='1', max_length=25)),
                ('purpose', models.CharField(choices=[('0', 'Rent'), ('1', 'Sale')], default='1', max_length=25)),
                ('year_built', models.PositiveIntegerField()),
                ('garage', models.PositiveIntegerField(blank=True, default=0)),
                ('floor', models.PositiveIntegerField()),
                ('total_floor', models.PositiveIntegerField(default=1)),
                ('internet', models.CharField(blank=True, max_length=50)),
                ('description', ckeditor.fields.RichTextField()),
                ('pet_policy', models.CharField(choices=[('0', 'Not Allowed'), ('1', 'Allowed'), ('2', 'Unknown')], default='0', max_length=50)),
                ('created', models.DateTimeField(auto_now=True)),
                ('featured', models.BooleanField(default=False)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='property.address')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='property.propertycategory')),
                ('feature', models.ManyToManyField(to='property.Feature')),
                ('picture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='property.picture')),
            ],
        ),
    ]
