# Generated by Django 3.1.1 on 2020-10-12 13:53

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='picture',
            name='created',
        ),
        migrations.RemoveField(
            model_name='picture',
            name='description',
        ),
        migrations.RemoveField(
            model_name='property',
            name='picture',
        ),
        migrations.AddField(
            model_name='picture',
            name='Property',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='images_created', to='property.property'),
        ),
        migrations.AddField(
            model_name='picture',
            name='created_at',
            field=models.DateTimeField(auto_now=True, db_index=True),
        ),
        migrations.AddField(
            model_name='picture',
            name='update_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='picture',
            name='title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
