# Generated by Django 3.1.1 on 2020-10-12 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0004_remove_property_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='short_description',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
