# Generated by Django 3.1.1 on 2020-11-17 22:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0011_auto_20201117_2137'),
    ]

    operations = [
        migrations.RenameField(
            model_name='property',
            old_name='user',
            new_name='publisher',
        ),
    ]
