# Generated by Django 3.1.1 on 2020-11-18 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0015_auto_20201117_2253'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='featured',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
